### ISSUE TITLE
Partial Support?

### ISSUE THREAD

**Issue by fanktom** [sstephenson/ruby-ejs#5]
Is there any way to get partials working?

I just tried to do it with `<%= this.partial('some_partial'); %>` but it doesn't work. I looked it up in the source and think it's not implemented yet, is it?

**Comment by sstephenson** [comment]
Compiled EJS templates are just JavaScript functions, which can be passed to other templates and invoked inside `<%= ... %>` tags.

**Comment by phillbaker** [comment]
A concrete example of @sstephenson's point above. (Note that this is from one .jst.ejs template to another in a rails app with backbone-rails.)

```
<backbone/templates/template>

Hey Ma, look at my sweet template!
<%= JST['backbone/templates/_some_partial']() %>
```

```
<backbone/templates/_some_partial>

Yo Pa, check out my partial!
```

=> 

```
Hey Ma, look at my sweet template!
Yo Pa, check out my partial!
```
